language: node_js
node_js:
  - "8.0.0"
before_install:
  - mysql -e 'CREATE DATABASE wx_boilerplate_test;'
install: npm install
script:
  - mv ./config/config.json.default ./config/config.json
  - NODE_ENV=test ./node_modules/.bin/jest --runInBand --notify --no-cache --silent --exitForce
cache:
  directories:
  - .node_modules
services:
  - redis-server
  - mysql