language: node_js
node_js:
  - "8.0.0"
before_install:
  - mysql -e 'CREATE DATABASE wx_boilerplate_test;'
install: npm install
script:
  - mv ./config/config.json.default ./config/config.json
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: NODE_ENV=test ./node_modules/.bin/jest --coverage --forceExit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
cache:
  directories:
  - .node_modules
services:
  - redis-server
  - mysql